import fs from "node:fs"; import path from "node:path"; import {execFileSync} from "node:child_process";
const root=process.cwd(),source=path.join(root,"Dulieutruyxuat","So sánh.xlsx"),work=path.join(root,"outputs","complete_standard_work"),xlsx=path.join(work,"xlsx"),ref=path.join(root,"outputs","compare_200_klg_with_csdl","ref");
const candidates=JSON.parse(fs.readFileSync(path.join(root,"outputs","csdl_candidates_for_standard.json"),"utf8"));
const read=p=>fs.readFileSync(p,"utf8"),write=(p,v)=>fs.writeFileSync(p,v),esc=(v="")=>String(v).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");
const dec=(v="")=>String(v).replace(/&#x([0-9a-f]+);/gi,(_,x)=>String.fromCodePoint(parseInt(x,16))).replace(/&#(\d+);/g,(_,x)=>String.fromCodePoint(Number(x))).replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&quot;/g,'"').replace(/&apos;/g,"'").replace(/&amp;/g,"&");
function colNo(ref){let n=0;for(const c of(String(ref).match(/^[A-Z]+/)?.[0]||""))n=n*26+c.charCodeAt(0)-64;return n;}function colName(n){let s="";while(n){const r=(n-1)%26;s=String.fromCharCode(65+r)+s;n=Math.floor((n-1)/26);}return s;}
function shared(dir){const p=path.join(dir,"xl","sharedStrings.xml");if(!fs.existsSync(p))return[];return[...read(p).matchAll(/<si\b[^>]*>([\s\S]*?)<\/si>/g)].map(m=>[...m[1].matchAll(/<t\b[^>]*>([\s\S]*?)<\/t>/g)].map(x=>dec(x[1])).join(""));}
function rows(dir,file,ss){const out=[];for(const m of read(path.join(dir,"xl","worksheets",file)).matchAll(/<row\b([^>]*)>([\s\S]*?)<\/row>/g)){const row=Number(m[1].match(/\br="(\d+)"/)?.[1]),v=new Map();for(const c of m[2].matchAll(/<c\b([^>]*?)(?:\/>|>([\s\S]*?)<\/c>)/g)){const a=c[1]||"",r=a.match(/\br="([^"]+)"/)?.[1];if(!r)continue;const t=a.match(/\bt="([^"]+)"/)?.[1]||"",b=c[2]||"";let x="";if(t==="s")x=ss[Number(b.match(/<v>([\s\S]*?)<\/v>/)?.[1])]||"";else if(t==="inlineStr")x=[...b.matchAll(/<t\b[^>]*>([\s\S]*?)<\/t>/g)].map(z=>dec(z[1])).join("");else x=dec(b.match(/<v>([\s\S]*?)<\/v>/)?.[1]||"");v.set(colNo(r),x);}out.push({row,v});}return out;}
function norm(v=""){return String(v).toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu,"").replace(/đ/g,"d").replace(/\b(ky luc gia|klg|gsdd|tsdd|gs|pgs|ts|ths|bs|pd|ong|ba|anh|chi|nghe nhan|nghe si|hoa si|nha suu tap|nha bao|nha nhiep anh|doanh nhan|luong y|dai duc|thuong toa|hoa thuong|nhac si|soan gia|dao dien|kien truc su|luat su|vo su|chuyen gia|ca si|dien vien|nha giao|nha van|nha tho|ky su|anh hung lao dong|giao su|bac si|tien si|thac si|phap danh|chau a|viet nam|the gioi)\b/g," ").replace(/[^a-z0-9]+/g," ").replace(/\s+/g," ").trim();}
function gabKey(v=""){return String(v).match(/gab\.world\/vi\/bank\/([^/?#]+)/i)?.[1]?.toLowerCase()||"";}function dateText(v=""){const s=String(v).trim();if(/^\d+(\.0+)?$/.test(s)){const n=Number(s);if(n>20000&&n<70000){const d=new Date(Date.UTC(1899,11,30)+n*86400000);return`${String(d.getUTCDate()).padStart(2,"0")}/${String(d.getUTCMonth()+1).padStart(2,"0")}/${d.getUTCFullYear()}`;}return/^(19|20)\d{2}$/.test(s)?s:"";}const dates=[...s.matchAll(/(\d{1,2})[./-](\d{1,2})[./-](\d{2,4})/g)];if(dates.length){const m=dates.at(-1),year=m[3].length===2?`20${m[3]}`:m[3];return`${m[1].padStart(2,"0")}/${m[2].padStart(2,"0")}/${year}`;}return "";}
const ss=shared(xlsx),standard=rows(xlsx,"sheet2.xml",ss).filter(r=>r.row>=3),initial=rows(xlsx,"sheet3.xml",ss).filter(r=>r.row>=3);
const gabByName=new Map();for(const r of initial){const n=norm(r.v.get(3)||""),g=String(r.v.get(2)||"").trim();if(n&&gabKey(g))gabByName.set(n,g);}
const rss=shared(ref),gabSheet=rows(ref,"sheet2.xml",rss);for(const r of gabSheet){const n=norm(r.v.get(2)||""),g=String(r.v.get(1)||"").trim();if(n&&gabKey(g)&&!gabByName.has(n))gabByName.set(n,g);}
const existing=new Set(standard.map(r=>`${norm(r.v.get(7)||"")}|${norm(r.v.get(5)||r.v.get(14)||"")}`));
function typeFor(s){return s==="CSDL KLVN"?"Kỷ lục Việt Nam":s==="CSDL KLVW"?"Kỷ lục Người Việt toàn cầu":s==="CSDL KL CA"?"Kỷ lục Châu Á":"Kỷ lục Thế giới";}
function cleanTitle(c){let lines=String(c.title||"").split(/\r?\n/).map(x=>x.trim()).filter(Boolean);if(lines.length>1&&norm(lines[0]).includes(norm(c.fullName)))lines.shift();while(lines.length>1&&/^\([^)]*vi[eệ]t nam[^)]*\)$/i.test(lines[0]))lines.shift();if(c.sheet==="CSDL KLTG"&&lines.length>1&&!/^\d+[.)]\s*/.test(lines[0]))return lines[0].trim();return lines.join(" ").replace(/^\d+[.)]\s*/,"").trim();}
function expandCandidate(c){const raw=String(c.title||"");const numbered=[...raw.matchAll(/(?:^|\n)\s*\d+[.)]\s*([^\n;]+(?:;|$)?)/g)].map(m=>m[1].replace(/;\s*$/,"").trim()).filter(Boolean);if(numbered.length<2)return[{...c,title:cleanTitle(c),date:dateText(c.date),id:String(c.id||"")}];const ids=String(c.id||"").split(/\r?\n|\s*;\s*/).map(x=>x.trim()).filter(x=>x&&x!=="----"),dates=String(c.date||"").split(/\r?\n|\s*;\s*/).map(dateText).filter(Boolean);return numbered.map((title,i)=>({...c,title,date:dates[i]||"",id:ids[i]||""}));}
const add=[];for(const sourceCandidate of candidates){for(const c of expandCandidate(sourceCandidate)){const title=c.title;if(!title)continue;const key=`${norm(c.fullName)}|${norm(title)}`;if(existing.has(key))continue;existing.add(key);const type=typeFor(c.sheet),date=c.date||dateText(c.date),gab=gabByName.get(norm(c.fullName))||"Chưa có GAB";add.push(["", "", c.id||"", date, title, gab, c.fullName, "", c.province||"", "", type.toUpperCase(), "", date, `Xác lập ${type} “${title}”`, c.link||"", "", "", "", `Bổ sung từ ${c.sheet}, dòng ${c.row}. ${c.link?"":"Cần bổ sung link bài viết và mô tả từ Kyluc.vn."}`, ""]);}}
let xml=read(path.join(xlsx,"xl","worksheets","sheet2.xml"));
const populatedRows=standard.filter(r=>[...r.v.values()].some(v=>String(v).trim()!=="")).map(r=>r.row);
const start=Math.max(2,...populatedRows)+1;
// The template contains hundreds of formatted but empty rows. Remove only those
// trailing placeholders so appended achievements stay directly below the data.
xml=xml.replace(/<row\b([^>]*)>([\s\S]*?)<\/row>/g,(whole,attrs,body)=>{
  const row=Number(attrs.match(/\br="(\d+)"/)?.[1]||0);
  if(row<start)return whole;
  const parsed=standard.find(item=>item.row===row);
  const hasValue=parsed&&[...parsed.v.values()].some(v=>String(v).trim()!=="");
  return hasValue?whole:"";
});
const sample=xml.match(/<row\b[^>]*\br="3"[^>]*>([\s\S]*?)<\/row>/)?.[1]||"",styles=new Map();for(const c of sample.matchAll(/<c\b([^>]*)/g)){const ref=c[1].match(/\br="([A-Z]+)3"/)?.[1],s=c[1].match(/\bs="(\d+)"/)?.[1];if(ref)styles.set(ref,s||"0");}
const cell=(v,ref,s)=>`<c r="${ref}" s="${s}" t="inlineStr"><is><t xml:space="preserve">${esc(v)}</t></is></c>`;const newRows=add.map((vals,i)=>{const n=start+i;return`<row r="${n}" ht="42" customHeight="1">${vals.map((v,j)=>cell(v,`${colName(j+1)}${n}`,styles.get(colName(j+1))||"1")).join("")}</row>`;}).join("");xml=xml.replace("</sheetData>",`${newRows}</sheetData>`);const last=start+add.length-1;xml=xml.replace(/<dimension ref="[^"]+"\/>/,`<dimension ref="A1:T${last}"/>`);write(path.join(xlsx,"xl","worksheets","sheet2.xml"),xml);
const zip=path.join(work,"with_csdl.zip"),temp=path.join(work,"So sánh.with_csdl.xlsx");if(fs.existsSync(zip))fs.rmSync(zip,{force:true});if(fs.existsSync(temp))fs.rmSync(temp,{force:true});execFileSync("powershell",["-NoProfile","-Command",`Add-Type -AssemblyName System.IO.Compression.FileSystem; [System.IO.Compression.ZipFile]::CreateFromDirectory('${xlsx.replace(/'/g,"''")}', '${zip.replace(/'/g,"''")}')`],{stdio:"pipe"});fs.copyFileSync(zip,temp);fs.copyFileSync(temp,source);console.log(JSON.stringify({candidateRecords:candidates.length,addedRows:add.length,startRow:start,lastRow:last,output:source},null,2));
