import fs from "node:fs";import path from "node:path";import{execFileSync}from"node:child_process";
const root=process.cwd(),work=path.join(root,"outputs","complete_standard_work"),xlsx=path.join(work,"xlsx"),source=path.join(root,"Dulieutruyxuat","So sánh.xlsx");
const V="KỶ LỤC VIỆT NAM",W="KỶ LỤC THẾ GIỚI",A="KỶ LỤC CHÂU Á";
const verified=[
["NGUYỄN QUANG MÂU","09/2020","Đơn vị sản xuất viên gạch Cotto siêu mịn lớn nhất thế giới (2600 mm x 600 mm)",W,"https://kyluc.vn/tin-tuc/ky-luc/gom-dat-viet-xac-lap-ky-luc-voi-vien-gach-cotto-sieu-min-lon-nhat-the-gioi"],
["NGUYỄN QUANG MÂU","21/09/2025","Sản xuất viên gạch Cotto siêu mịn phủ men Granite có kích thước lớn nhất thế giới",W,"https://kyluc.vn/tin-tuc/ky-luc-the-gioi/gom-dat-viet-tiep-tuc-khang-dinh-chat-luong-bang-lan-chinh-phuc-ky-luc-the-gioi-lan-thu-5"],
["TRẦN HỮU HUỆ","04/02/2026","Được vinh danh 02 Kỷ lục Việt Nam với hành trình 60 năm sưu tập tem bưu chính",V,"https://kyluc.vn/tin-tuc/ky-luc/tran-huu-hue-lao-nong-me-tem-o-an-giang-duoc-vinh-danh-02-ky-luc-viet-nam-voi-hanh-trinh-60-nam-suu-tap-tem-buu-chinh"],
["VƯƠNG THỊ MÙI EM","04/02/2026","Đồng hành gìn giữ, sưu tập tem bưu chính trong hành trình 60 năm được vinh danh Kỷ lục Việt Nam",V,"https://kyluc.vn/tin-tuc/ky-luc/tran-huu-hue-lao-nong-me-tem-o-an-giang-duoc-vinh-danh-02-ky-luc-viet-nam-voi-hanh-trinh-60-nam-suu-tap-tem-buu-chinh"],
["KHÚC THỊ DẬU","22/06/2025","Bộ sưu tập máy may của các nước trên thế giới sản xuất trước năm 1955 có số lượng nhiều nhất (300 chiếc)","KỶ LỤC NGƯỜI VIỆT TOÀN CẦU","https://kyluc.vn/tin-tuc/ky-luc/ky-luc-gia-dao-xuan-tinh-xac-lap-ky-luc-moi-voi-bo-suu-tap-hon-300-may-may-co"],
["LÊ TÂN","","Đồng tổ chức chế biến hơn 1.000 đĩa Bún xào Thập cẩm kiểu Huế phục vụ nhiều thực khách cùng lúc",V,"https://kyluc.vn/tin-tuc/ky-luc/ve-tham-co-do-thuong-thuc-mon-bun-xao-thap-cam-kieu-hue-vua-xac-lap-ky-luc-viet-nam"],
["TRẦN NHẬT TRƯỜNG","","Sự kiện quy tụ 100 đầu bếp mặc trang phục truyền thống Nam Bộ cùng tham gia đổ bánh xèo - số lượng nhiều nhất Việt Nam",V,"https://kyluc.vn/tin-tuc/ky-luc/ve-an-giang-tham-du-le-hoi-vu-lan-bao-hieu-thien-cam-son-chiem-nguong-man-trinh-dien-do-banh-xeo-xac-lap-ky-luc-viet-nam"],
["ĐẶNG MINH THƯ","23/06/2026","Xác lập cú đúp Kỷ lục Học đường tại Việt Nam về khả năng ghi nhớ số Pi","KỶ LỤC HỌC ĐƯỜNG VIỆT NAM","https://kyluc.vn/tin-tuc/ky-luc-viet-nam/nu-sinh-lop-5-dang-minh-thu-lap-cu-dup-ky-luc-moi-ve-ghi-nho-so-pi"],
["HOÀNG THỊ PHƯỢNG","","Nơi hội tụ và tỏa sáng nét chữ Việt - Tác phẩm độc bản tuyển chọn bài viết và bài dự thi viết chữ đẹp có số lượng nhiều nhất (1.018 bài)",V,"https://kyluc.vn/tin-tuc/ky-luc/tac-pham-noi-hoi-tu-va-toa-sang-net-chu-viet-xac-lap-ky-luc-doc-ban-viet-nam"],
["DƯƠNG VĂN CHIẾN","27/08/2020","Đơn vị đầu tư, tư vấn đầu tư, xây dựng, quản lý và kinh doanh hệ thống chợ trên toàn quốc nhiều nhất",V,"https://kyluc.vn/tin-tuc/ky-luc-viet-nam/hop-tac-xa-dau-tu-xay-dung-quan-ly-va-khai-thac-cho-hai-an-xac-lap-ky-luc-viet-nam"],
["NGUYỄN TRẦN LỘC","2016","Ảo thuật gia biến đổi trang phục truyền thống và dạ hội nhiều nhất trong thời gian ngắn nhất",V,"https://kyluc.vn/tin-tuc/ky-luc-viet-nam/nghe-si-hoang-loc-ao-thuat-la-su-gan-bo-mau-thit-va-niem-dam-me-chay-bong"],
["TRỊNH TRỌNG GIỮ","","Doanh nhân, cựu chiến binh sáng tạo và sưu tầm hơn 2.500 mẫu kỷ niệm chương, huy chương, cúp lưu niệm trong hơn 20 năm - số lượng nhiều nhất Việt Nam",V,"https://kyluc.vn/tin-tuc/ky-luc-the-gioi/worldkings-vinh-danh-ky-luc-gia-trinh-trong-giu-danh-hieu-grand-records-tinh-hoa-ky-luc"],
["TẠ HUY HOÀNG","10/08/2020","Linh mục xuất bản bộ sách Sỏi đá vẫn cần có nhau - ấn phẩm Công giáo nhiều tập nhất với các đề tài phong phú (trên 10.000 số)",V,"https://kyluc.vn/tin-tuc/ky-luc/linh-muc-ky-luc-gia-the-gioi-ta-huy-hoang-duoc-vinh-danh-giai-thuong-grand-records-tinh-hoa-ky-luc"],
["TẠ HUY HOÀNG","20/12/2020","Linh mục biên soạn và xuất bản các ấn phẩm sách học tiếng Anh bằng ngữ liệu của Giáo hội Công giáo nhiều nhất",V,"https://kyluc.vn/tin-tuc/cac-ban-quyen-su-kien-ky-luc/hoi-ngo-ky-luc-gia-viet-nam-lan-thu-41-cuoc-gap-go-cua-500-ky-luc-gia-tron-doi-sang-tao-tinh-hoa"],
["TẠ HUY HOÀNG","20/12/2020","Linh mục xuất bản các ấn phẩm giáo dục để giảng dạy về Thần học mục vụ và ngôn ngữ trong Giáo hội Công giáo Việt Nam nhiều nhất",V,"https://kyluc.vn/tin-tuc/cac-ban-quyen-su-kien-ky-luc/hoi-ngo-ky-luc-gia-viet-nam-lan-thu-41-cuoc-gap-go-cua-500-ky-luc-gia-tron-doi-sang-tao-tinh-hoa"],
["TẠ HUY HOÀNG","29/09/2022","Linh mục đầu tiên biên soạn và xuất bản bộ sách Hiểu và sống Tin-Cậy-Mến gồm 7 tập và hơn 400 video hướng dẫn",V,"https://kyluc.vn/tin-tuc/ky-luc-the-gioi/linh-muc-ky-luc-gia-the-gioi-ta-huy-hoang-duoc-vinh-danh-giai-thuong-grand-records-tinh-hoa-ky-luc"],
["TẠ HUY HOÀNG","2024","LAGAM: 25 năm nhìn lại - công trình hơn 30.000 trang, hàng ngàn video minh họa với 5 chủ đề học thuật","KỶ LỤC VIỆT NAM VÀ THẾ GIỚI","https://kyluc.vn/tin-tuc/ky-luc/lagam-25-nam-nhin-lai-cong-trinh-ky-luc-viet-nam-va-the-gioi-den-tu-mot-trai-tim-phung-su-cua-gs-ts-linh-muc-ta-huy-hoang"],
["ĐẶNG HUY TUÂN","11/2015","Công trình Nhà thờ Tổ họ Đặng Huy được xác lập giá trị độc bản tại Việt Nam","KỶ LỤC ĐỘC BẢN VIỆT NAM","https://kyluc.vn/tin-tuc/doc-ban/trao-bang-xac-lap-gia-tri-doc-ban-ky-luc-cho-con-trinh-nha-tho-to-ho-dang-huy"],
["HỒ QUANG MINH","2017","Sự kiện có nhiều doanh nhân trong và ngoài nước cùng mặc trang phục áo dài truyền thống Việt Nam nhất",V,"https://kyluc.vn/tin-tuc/ky-luc-the-gioi/ong-ho-quang-minh-chu-tich-bni-viet-nam-don-nhan-dia-vang-cong-hien-cua-vien-noi-dung-ky-luc-the-gioi-wrca"],
["HỒ QUANG MINH","2022","Sự kiện có số lượng doanh nhân là thành viên BNI nhiều nhất cùng ký tên lên bức tranh 10 điểm đến Đà Nẵng",V,"https://kyluc.vn/tin-tuc/ky-luc/hoi-ngo-dinh-cao-2022-1000-doanh-nhan-cua-bni-viet-nam-cung-tham-gia-ky-ten-len-buc-tranh-ve-da-nang-xac-lap-ky-luc"],
["NGUYỄN ĐĂNG GIÁP","06/01/2024","Như tôi đã sống - Tập hồi ký bằng văn xuôi được chuyển thể thành truyện thơ cùng tên có số lượng câu thơ lục bát nhiều nhất (3.836 câu)",V,"https://kyluc.vn/tin-tuc/ky-luc/nhu-toi-da-song-ban-hoa-tau-truyen-tho-cua-mot-anh-hung-lao-dong-thoi-ky-doi-moi-dai-ta-nguyen-dang-giap"],
["NGUYỄN ĐĂNG GIÁP","06/2025","Người có đóng góp tiên phong, xuất sắc trong lãnh đạo, đưa một đội sản xuất nhỏ thành Tổng công ty trực thuộc Bộ Quốc phòng trong 8 năm","TÔN VINH GIÁ TRỊ KỶ LỤC VIỆT NAM","https://kyluc.vn/tin-tuc/ky-luc-viet-nam/dai-ta-anh-hung-lao-dong-nguyen-dang-giap-va-dau-an-thuong-hieu-tong-cong-ty-36"],
["CHU TẤN SĨ","15/02/2019","Kíp trưởng ca mổ u não bằng Robot Modus V Synaptive đầu tiên thành công tại Bệnh viện Nhân dân 115",V,"https://kyluc.vn/tin-tuc/ky-luc/thay-thuoc-uu-tu-thac-si-bac-si-chu-tan-si-ban-tay-vang-phau-thuat-ngoai-than-kinh-va-ca-mo-lich-su-bang-robot-modus-v-synaptive"],
["THÍCH THANH CƯỜNG","","Chùa Cương Xá - Hệ thống tường đá khắc chữ Vạn","KỶ LỤC CHÂU Á","https://kyluc.vn/tin-tuc/ky-luc/hai-phong-chua-cuong-xa-don-nhan-ky-luc-chau-a-voi-he-thong-tuong-da-khac-chu-van"],
["LÝ NGỌC BẠCH","","Đại ấm Lạc Hồng - tác phẩm ấm nghệ thuật mang hoa văn trống đồng","KỶ LỤC ĐỊA PHƯƠNG BÌNH DƯƠNG","https://kyluc.vn/tin-tuc/ky-luc-the-gioi/cac-ky-luc-viet-nam-va-ky-luc-dia-phuong-binh-duong-lan-ii"],
["LÊ TRUNG ĐỨC","2025","Người tiên phong đưa hệ thống chăm sóc sức khỏe European Wellness từ châu Âu về Việt Nam (từ năm 2023)",V,"https://kyluc.vn/tin-tuc/nha-sang-nghiep/wowtimes-vietkings-ong-le-trung-duc-nguoi-tien-phong-dua-he-thong-cham-soc-suc-khoe-european-wellness-ve-viet-nam"],
["TRẦN THỊ HOÀNG LAN","2004","Người tìm được nhiều màu cát nhất với 30 màu",V,"https://kyluc.vn/tin-tuc/ky-luc/nghe-nhan-y-lan-doi-tay-vang-khai-sinh-dong-tranh-cat-viet-nam"],
["TRẦN THỊ HOÀNG LAN","2008","Người tìm được 81 màu cát tự nhiên","KỶ LỤC CHÂU Á","https://kyluc.vn/tin-tuc/ky-luc/vien-noi-dung-ky-luc-the-gioi-wrca-vinh-danh-nhung-cong-hien-ve-gia-tri-noi-dung-ky-luc-cua-ky-luc-gia-chau-a-tran-thi-hoang-lan-nghe-danh-y-lan"],
["TRẦN THỊ HOÀNG LAN","","Người đầu tiên sáng tạo ra tranh cát tại Việt Nam",V,"https://kyluc.vn/tin-tuc/ky-luc/vietkings-values-hanh-trinh-quang-ba-ky-luc-viet-nam-p-171-nghe-nhan-y-lan-nguoi-dau-tien-sang-tao-ra-tranh-cat"],
["NGUYỄN THỊ PHƯƠNG THẢO","22/10/2024","Nữ tỷ phú đô la đầu tiên của Việt Nam","TOP 500 KỶ LỤC BẤT BIẾN VIỆT NAM - ĐỀ CỬ","https://kyluc.vn/tin-tuc/de-xuat-ky-luc/vietkings-topplus-de-cu-lan-1-2024-top-500-ky-luc-bat-bien-viet-nam-p-291-nguyen-thi-phuong-thao-nu-ty-phu-do-la-dau-tien-cua-viet-nam"]
];
const unresolved=["NGÔ THỊ HOÀNG NGÂN","TRẦN QUANG LÂN","NGUYỄN NGỌC PHƯƠNG LAM","TRIỆU THỊ QUỲNH TRANG","TRẦN VĂN TOẢN","NGUYỄN THỊ KIM OANH","NGUYỄN QUANG THẮNG","TRẦN VĂN PHÁT","VÕ THỊ ÁNH NGUYỆT","NGUYÊN MẠNH PHƯƠNG (NGUYẼN PHƯƠNG)","LÊ THỊ ÚT","ĐẶNG HỒNG MI","NGÔ THU AN","TRẦN QUỐC HUY","NGUYỄN HOÀNG BÁCH","TRẦN HOÀI THUẬN","LƯƠNG THÀNH NHẬT","HUỲNH HOÀNG SƠN"];
const rows=[...verified.map(x=>({x,note:"Bổ sung từ bài Kyluc.vn đã kiểm chứng."})),...unresolved.map(name=>({x:[name,"","","CHƯA XÁC MINH",""],note:"CHƯA XÁC MINH ĐƯỢC NGUỒN: đã tra tên chính xác trên Kyluc.vn nhưng chưa tìm thấy bài thành tựu đủ căn cứ; giữ dòng để bảo đảm đủ danh sách Full."}))];
const esc=v=>String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;"),col=n=>{let s="";while(n){s=String.fromCharCode(65+(n-1)%26)+s;n=Math.floor((n-1)/26);}return s;};
const file=path.join(xlsx,"xl","worksheets","sheet2.xml");let xml=fs.readFileSync(file,"utf8"),start=Math.max(...[...xml.matchAll(/<row\b[^>]*\br="(\d+)"/g)].map(m=>+m[1]))+1;const sample=xml.match(/<row\b[^>]*\br="3"[^>]*>([\s\S]*?)<\/row>/)?.[1]||"",styles=new Map();for(const c of sample.matchAll(/<c\b([^>]*)/g)){const k=c[1].match(/\br="([A-Z]+)3"/)?.[1],s=c[1].match(/\bs="(\d+)"/)?.[1];if(k)styles.set(k,s||"0");}const cell=(v,r,c)=>`<c r="${c}${r}" s="${styles.get(c)||1}" t="inlineStr"><is><t xml:space="preserve">${esc(v)}</t></is></c>`;
const block=rows.map((o,i)=>{const r=start+i,[name,date,title,type,url]=o.x,vals=["","","",date,title,"Chưa có GAB",name,"","","",type,"",date,title?`Xác lập ${type.toLowerCase()} “${title}”`:"",url,"","","",o.note,""];return`<row r="${r}" ht="42" customHeight="1">${vals.map((v,j)=>cell(v,r,col(j+1))).join("")}</row>`}).join("");const last=start+rows.length-1;xml=xml.replace("</sheetData>",`${block}</sheetData>`).replace(/<dimension ref="[^"]+"\/>/,`<dimension ref="A1:T${last}"/>`);fs.writeFileSync(file,xml);const zip=path.join(work,"round2.zip");if(fs.existsSync(zip))fs.rmSync(zip,{force:true});execFileSync("powershell",["-NoProfile","-Command",`Add-Type -AssemblyName System.IO.Compression.FileSystem; [IO.Compression.ZipFile]::CreateFromDirectory('${xlsx.replace(/'/g,"''")}','${zip.replace(/'/g,"''")}')`]);fs.copyFileSync(zip,source);console.log(JSON.stringify({verified:verified.length,unresolved:unresolved.length,start,last},null,2));
