import fs from "node:fs";
import path from "node:path";
import {execFileSync} from "node:child_process";

const root=process.cwd(),work=path.join(root,"outputs","complete_standard_work"),xlsx=path.join(work,"xlsx");
const source=path.join(root,"Dulieutruyxuat","So sánh.xlsx");
const records=[
  ["CHU THỊ HẰNG","21/09/2025","Người đầu tiên hướng dẫn, truyền dạy làn điệu dân ca quan họ cổ bằng tiếng Việt cho nghệ sĩ Ấn Độ bằng hình thức trực tiếp và trực tuyến để phục vụ trong dự án phim truyền hình","KỶ LỤC VIỆT NAM","https://kyluc.vn/tin-tuc/ky-luc/gap-go-nu-nghe-si-viet-nam-dau-tien-truyen-day-cac-lan-dieu-dan-ca-quan-ho-co-cho-cac-ca-si-nghe-si-cua-an-do"],
  ["NGUYỄN VĂN ĐỆ","2020","Bệnh viện tư nhân tuyến tỉnh có số lượng giường bệnh đã đi vào hoạt động nhiều nhất (tính đến tháng 8 năm 2019)","KỶ LỤC VIỆT NAM","https://kyluc.vn/tin-tuc/nha-sang-nghiep/wowtime-vietkings-nien-lich-thanh-tuu-2025-hop-luc-group-hanh-trinh-ba-thap-ky-kien-tao-gia-tri-ben-vung-cho-cong-dong"],
  ["NGUYỄN VĂN ĐỆ","2020","Đơn vị cung cấp và lắp đặt thiết bị lò hỏa táng Tabo thân thiện với môi trường nhiều nhất Việt Nam (tính từ 2018 đến năm 2020)","KỶ LỤC VIỆT NAM","https://kyluc.vn/tin-tuc/nha-sang-nghiep/wowtime-vietkings-nien-lich-thanh-tuu-2025-hop-luc-group-hanh-trinh-ba-thap-ky-kien-tao-gia-tri-ben-vung-cho-cong-dong"],
  ["LÊ VĂN DŨNG","25/10/2013","Cửu Long tranh châu - tác phẩm chế tác từ ngọc Pakistan nguyên khối","KỶ LỤC CHÂU Á","https://kyluc.vn/tin-tuc/nha-sang-nghiep/wowtimes-nien-lich-thanh-tuu-viet-nam-2023-cong-ty-tnhh-dung-tan-chang-duong-16-nam-hoat-dong-cua-khong-gian-sinh-canh-dep-bac-nhat-mien-bac-viet-nam"],
  ["LÊ VĂN DŨNG","06/12/2020","Khu sân vườn - hồ cá Koi Nhật Bản sử dụng nhiều đá bán quý nhất tại Việt Nam","KỶ LỤC VIỆT NAM","https://kyluc.vn/tin-tuc/nha-sang-nghiep/wowtimes-nien-lich-thanh-tuu-viet-nam-2023-cong-ty-tnhh-dung-tan-chang-duong-16-nam-hoat-dong-cua-khong-gian-sinh-canh-dep-bac-nhat-mien-bac-viet-nam"],
  ["LÊ VĂN DŨNG","15/12/2022","Vũ điệu Thiên nga - Cây Bonsai Tùng Kim Cương","KỶ LỤC ĐỘC BẢN VIỆT NAM","https://kyluc.vn/tin-tuc/nha-sang-nghiep/wowtimes-nien-lich-thanh-tuu-viet-nam-2023-cong-ty-tnhh-dung-tan-chang-duong-16-nam-hoat-dong-cua-khong-gian-sinh-canh-dep-bac-nhat-mien-bac-viet-nam"],
  ["MAI XUÂN THẮNG","","Lâu đài dát vàng trưng bày và giới thiệu nhiều loại rượu vang quốc tế nhất tại Việt Nam","KỶ LỤC VIỆT NAM","https://kyluc.vn/tin-tuc/ky-luc/hoi-ngo-cac-ky-luc-gia-viet-nam-lan-thu-52-xac-lap-va-vinh-danh-nhieu-ky-luc-viet-nam-tieu-bieu-trong-nam-2022-2023"],
  ["NGUYỄN VĂN CÔNG (THIỆN HẢO)","21/10/2019","Nhạc sĩ sáng tác 200 bản nhạc được đăng ký bản quyền trong vòng 6 tháng","KỶ LỤC VIỆT NAM","https://kyluc.vn/tin-tuc/ky-luc/nhac-si-thien-hao-lap-ky-luc-voi-200-ban-nhac-sang-tac-trong-vong-6-thang-vo-la-nguon-cam-hung-bat-tan"],
  ["NGUYỄN VĂN CÔNG (THIỆN HẢO)","06/08/2024","Nhạc sĩ sáng tác và được cấp Bản quyền Tác giả cho nhiều ca khúc nhất trong thời gian 6 năm (2018-2024, với 400 ca khúc)","KỶ LỤC VIỆT NAM","https://kyluc.vn/tin-tuc/ky-luc/nhac-si-thien-hao-lap-ky-luc-viet-nam-voi-400-ca-khuc-duoc-sang-tac-va-dang-ky-ban-quyen-trong-thoi-gian-6-nam"],
  ["NGUYỄN VĂN CÔNG (THIỆN HẢO)","03/06/2025","Nhạc sĩ sáng tác và được cấp Bản quyền Tác giả cho nhiều ca khúc nhất trong thời gian 4 tháng (12/2024-03/2025, với 306 ca khúc)","KỶ LỤC VIỆT NAM","https://kyluc.vn/tin-tuc/ky-luc-viet-nam/nhac-si-thien-hao-lan-thu-3-xac-lap-ky-luc-viet-nam-trong-linh-vuc-ban-quyen-tac-pham-am-nhac"],
  ["VÕ DƯƠNG","29/06/2019","Đại tướng của nhân dân, Võ Nguyên Giáp - những năm tháng cuộc đời: Cuốn đại sách thư pháp về Đại tướng Võ Nguyên Giáp","KỶ LỤC THẾ GIỚI","https://kyluc.vn/tin-tuc/ky-luc/sach-thu-phap-ve-dai-tuong-vo-nguyen-giap-xac-lap-ky-luc-viet-nam"],
  ["KEVIN NGUYỄN KIÊN TRÌ","07/12/2024","Người huấn luyện doanh nghiệp - Business Coach đạt chứng chỉ quốc tế lâu năm, có tổng thời gian phụ trách các buổi huấn luyện cho cá nhân, đơn vị nhiều nhất trong 8 năm liên tục","KỶ LỤC VIỆT NAM","https://kyluc.vn/tin-tuc/ky-luc/thac-si-kevin-nguyen-kien-tri-lap-cu-dup-ky-luc-viet-nam-nhan-ngay-ra-mat-sach-va-ky-niem-08-nam-lam-business-coach"],
  ["KEVIN NGUYỄN KIÊN TRÌ","07/12/2024","Tối ưu doanh nghiệp - Đột phá cùng Business Coach: Cuốn sách chủ đề Business Coach dành cho doanh nghiệp vừa và nhỏ, mang yếu tố huấn luyện tương tác đầu tiên được biên soạn và xuất bản tại Việt Nam","KỶ LỤC VIỆT NAM","https://kyluc.vn/tin-tuc/ky-luc/thac-si-kevin-nguyen-kien-tri-lap-cu-dup-ky-luc-viet-nam-nhan-ngay-ra-mat-sach-va-ky-niem-08-nam-lam-business-coach"]
];
const esc=v=>String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");
const col=n=>{let s="";while(n){s=String.fromCharCode(65+(n-1)%26)+s;n=Math.floor((n-1)/26);}return s;};
const file=path.join(xlsx,"xl","worksheets","sheet2.xml");let xml=fs.readFileSync(file,"utf8");
const rows=[...xml.matchAll(/<row\b[^>]*\br="(\d+)"[^>]*>([\s\S]*?)<\/row>/g)];const start=Math.max(...rows.map(m=>Number(m[1])))+1;
const sample=xml.match(/<row\b[^>]*\br="3"[^>]*>([\s\S]*?)<\/row>/)?.[1]||"",styles=new Map();for(const c of sample.matchAll(/<c\b([^>]*)/g)){const a=c[1],k=a.match(/\br="([A-Z]+)3"/)?.[1],s=a.match(/\bs="(\d+)"/)?.[1];if(k)styles.set(k,s||"0");}
const cell=(v,r,c)=>`<c r="${c}${r}" s="${styles.get(c)||1}" t="inlineStr"><is><t xml:space="preserve">${esc(v)}</t></is></c>`;
const added=records.map((x,i)=>{const r=start+i,[name,date,title,type,url]=x;const vals=["","","",date,title,"Chưa có GAB",name,"","","",type,"",date,`Xác lập ${type.toLowerCase()} “${title}”`,url,"","","","Bổ sung từ bài Kyluc.vn đã kiểm chứng.",""];return`<row r="${r}" ht="42" customHeight="1">${vals.map((v,j)=>cell(v,r,col(j+1))).join("")}</row>`;}).join("");
xml=xml.replace("</sheetData>",`${added}</sheetData>`).replace(/<dimension ref="[^"]+"\/>/,`<dimension ref="A1:T${start+records.length-1}"/>`);fs.writeFileSync(file,xml);
const zip=path.join(work,"verified_web.zip");if(fs.existsSync(zip))fs.rmSync(zip,{force:true});execFileSync("powershell",["-NoProfile","-Command",`Add-Type -AssemblyName System.IO.Compression.FileSystem; [System.IO.Compression.ZipFile]::CreateFromDirectory('${xlsx.replace(/'/g,"''")}','${zip.replace(/'/g,"''")}')`]);fs.copyFileSync(zip,source);console.log(JSON.stringify({added:records.length,start,last:start+records.length-1,source},null,2));
