import fs from "node:fs"; import path from "node:path";
const root=process.cwd(),cur=path.join(root,"outputs","complete_standard_work","xlsx"),ref=path.join(root,"outputs","compare_200_klg_with_csdl","ref");
const read=p=>fs.readFileSync(p,"utf8"),dec=(v="")=>String(v).replace(/&#x([0-9a-f]+);/gi,(_,x)=>String.fromCodePoint(parseInt(x,16))).replace(/&#(\d+);/g,(_,x)=>String.fromCodePoint(Number(x))).replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&quot;/g,'"').replace(/&apos;/g,"'").replace(/&amp;/g,"&");
function col(ref){let n=0;for(const c of(String(ref).match(/^[A-Z]+/)?.[0]||""))n=n*26+c.charCodeAt(0)-64;return n;}
function shared(dir){const p=path.join(dir,"xl","sharedStrings.xml");if(!fs.existsSync(p))return[];return[...read(p).matchAll(/<si\b[^>]*>([\s\S]*?)<\/si>/g)].map(m=>[...m[1].matchAll(/<t\b[^>]*>([\s\S]*?)<\/t>/g)].map(x=>dec(x[1])).join(""));}
function rows(dir,file,ss){const out=[];for(const m of read(path.join(dir,"xl","worksheets",file)).matchAll(/<row\b([^>]*)>([\s\S]*?)<\/row>/g)){const row=Number(m[1].match(/\br="(\d+)"/)?.[1]),v=new Map();for(const c of m[2].matchAll(/<c\b([^>]*?)(?:\/>|>([\s\S]*?)<\/c>)/g)){const a=c[1]||"",r=a.match(/\br="([^"]+)"/)?.[1];if(!r)continue;const t=a.match(/\bt="([^"]+)"/)?.[1]||"",b=c[2]||"";let x="";if(t==="s")x=ss[Number(b.match(/<v>([\s\S]*?)<\/v>/)?.[1])]||"";else if(t==="inlineStr")x=[...b.matchAll(/<t\b[^>]*>([\s\S]*?)<\/t>/g)].map(z=>dec(z[1])).join("");else x=dec(b.match(/<v>([\s\S]*?)<\/v>/)?.[1]||"");v.set(col(r),x);}out.push({row,v});}return out;}
function sheets(dir){const wb=read(path.join(dir,"xl","workbook.xml")),re=read(path.join(dir,"xl","_rels","workbook.xml.rels")),rm=new Map([...re.matchAll(/<Relationship\b([^>]*)\/>/g)].map(m=>[m[1].match(/\bId="([^"]+)"/)?.[1],m[1].match(/\bTarget="([^"]+)"/)?.[1]])),o=new Map();for(const m of wb.matchAll(/<sheet\b([^>]*)\/>/g)){const a=m[1],n=dec(a.match(/\bname="([^"]+)"/)?.[1]||""),id=a.match(/\br:id="([^"]+)"/)?.[1];let t=rm.get(id);if(t){t=t.replace(/^\/?xl\//,"").replace(/^worksheets\//,"");o.set(n,t);}}return o;}
function norm(v=""){return String(v).toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu,"").replace(/đ/g,"d").replace(/\b(ky luc gia|klg|gsdd|tsdd|gs|pgs|ts|ths|bs|pd|ong|ba|anh|chi|nghe nhan|nghe si|hoa si|nha suu tap|nha bao|nha nhiep anh|doanh nhan|luong y|dai duc|thuong toa|hoa thuong|nhac si|soan gia|dao dien|kien truc su|luat su|vo su|chuyen gia|ca si|dien vien|nha giao|nha van|nha tho|ky su|anh hung lao dong|giao su|bac si|tien si|thac si|phap danh|chau a|viet nam|the gioi)\b/g," ").replace(/[^a-z0-9]+/g," ").replace(/\s+/g," ").trim();}
function variants(v=""){const s=String(v),o=new Set([norm(s),norm(s.replace(/\([^)]*\)/g," "))]);for(const m of s.matchAll(/\(([^)]+)\)/g))o.add(norm(m[1]));return[...o].filter(Boolean);}
function gab(v=""){return String(v).match(/gab\.world\/vi\/bank\/([^/?#]+)/i)?.[1]?.toLowerCase()||"";}
const css=shared(cur),full=rows(cur,"sheet6.xml",css).filter(r=>r.row>1).map(r=>String(r.v.get(3)||"").trim()).filter(Boolean);
const standardRows=rows(cur,"sheet2.xml",css).filter(r=>r.row>2).map(r=>({name:String(r.v.get(7)||"").trim(),gab:gab(r.v.get(6)||"")})).filter(r=>r.name);
const standard=new Set(standardRows.flatMap(r=>variants(r.name))),standardGabs=new Set(standardRows.map(r=>r.gab).filter(Boolean));
const initialRows=rows(cur,"sheet3.xml",css).filter(r=>r.row>2).map(r=>({name:String(r.v.get(3)||"").trim(),gab:gab(r.v.get(2)||"")})).filter(r=>r.name);
function inStandard(name){const vs=variants(name);if(vs.some(v=>standard.has(v)))return true;const initials=initialRows.filter(r=>variants(r.name).some(v=>vs.includes(v)));return initials.some(r=>r.gab&&standardGabs.has(r.gab));}
const rss=shared(ref),sm=sheets(ref),owners=new Map();for(const sn of["CSDL KLVN","CSDL KLVW","CSDL KL CA","CSDL KLTG"]){const file=sm.get(sn);if(!file)continue;for(const r of rows(ref,file,rss)){if(r.row<3)continue;const ownerCol=sn==="CSDL KLVN"?6:sn==="CSDL KLVW"?7:2,owner=String(r.v.get(ownerCol)||"").trim();if(!owner)continue;const item=sn==="CSDL KLVN"?{sheet:sn,row:r.row,owner,id:String(r.v.get(3)||"").trim(),date:String(r.v.get(4)||"").trim(),title:String(r.v.get(5)||"").trim(),link:"",province:String(r.v.get(7)||"").trim(),field:String(r.v.get(8)||"").trim()}:sn==="CSDL KLVW"?{sheet:sn,row:r.row,owner,id:String(r.v.get(4)||"").trim(),date:String(r.v.get(5)||"").trim(),title:String(r.v.get(6)||"").trim(),link:"",province:String(r.v.get(8)||"").trim(),field:""}:{sheet:sn,row:r.row,owner,id:String(r.v.get(4)||"").trim(),date:String(r.v.get(5)||r.v.get(4)||"").trim(),title:String(r.v.get(3)||"").trim(),link:String(r.v.get(6)||"").trim(),province:String(r.v.get(7)||"").trim(),field:""};const k=norm(owner);if(!owners.has(k))owners.set(k,[]);owners.get(k).push(item);}}
const out=full.map(name=>({name,key:norm(name),standard:inStandard(name),csdl:Math.max(...variants(name).map(v=>(owners.get(v)||[]).length),0)}));
const candidates=out.filter(x=>!x.standard&&x.csdl).flatMap(x=>{for(const v of variants(x.name)){const a=owners.get(v);if(a?.length)return a.map(r=>({...r,fullName:x.name}));}return[];});
fs.writeFileSync(path.join(root,"outputs","csdl_candidates_for_standard.json"),JSON.stringify(candidates,null,2));
console.log(JSON.stringify({full:out.length,inStandard:out.filter(x=>x.standard).length,notStandard:out.filter(x=>!x.standard).length,notStandardButCSDL:out.filter(x=>!x.standard&&x.csdl).length,noLocalSource:out.filter(x=>!x.standard&&!x.csdl).length,namesWithCSDL:out.filter(x=>!x.standard&&x.csdl).map(x=>({name:x.name,records:x.csdl})),namesNoLocal:out.filter(x=>!x.standard&&!x.csdl).map(x=>x.name)},null,2));
