import fs from "node:fs";
import path from "node:path";
import { execFileSync } from "node:child_process";

const root=process.cwd(),source=path.join(root,"Dulieutruyxuat","So sánh.xlsx"),work=path.join(root,"outputs","audit_full200_refresh"),xlsx=path.join(work,"xlsx");
const read=p=>fs.readFileSync(p,"utf8"),write=(p,v)=>fs.writeFileSync(p,v);
const esc=(v="")=>String(v).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");
const dec=(v="")=>String(v).replace(/&#x([0-9a-f]+);/gi,(_,x)=>String.fromCodePoint(parseInt(x,16))).replace(/&#(\d+);/g,(_,x)=>String.fromCodePoint(Number(x))).replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&quot;/g,'"').replace(/&apos;/g,"'").replace(/&amp;/g,"&");
function colNo(ref){let n=0;for(const c of(String(ref).match(/^[A-Z]+/)?.[0]||""))n=n*26+c.charCodeAt(0)-64;return n;}
function colName(n){let s="";while(n){const r=(n-1)%26;s=String.fromCharCode(65+r)+s;n=Math.floor((n-1)/26);}return s;}
function shared(){const p=path.join(xlsx,"xl","sharedStrings.xml");if(!fs.existsSync(p))return[];return[...read(p).matchAll(/<si\b[^>]*>([\s\S]*?)<\/si>/g)].map(m=>[...m[1].matchAll(/<t\b[^>]*>([\s\S]*?)<\/t>/g)].map(x=>dec(x[1])).join(""));}
function rows(file,strings){const out=[];for(const m of read(path.join(xlsx,"xl","worksheets",file)).matchAll(/<row\b([^>]*)>([\s\S]*?)<\/row>/g)){const row=Number(m[1].match(/\br="(\d+)"/)?.[1]),values=new Map();for(const c of m[2].matchAll(/<c\b([^>]*?)(?:\/>|>([\s\S]*?)<\/c>)/g)){const attrs=c[1]||"",ref=attrs.match(/\br="([^"]+)"/)?.[1];if(!ref)continue;const type=attrs.match(/\bt="([^"]+)"/)?.[1]||"",body=c[2]||"";let value="";if(type==="s")value=strings[Number(body.match(/<v>([\s\S]*?)<\/v>/)?.[1])]||"";else if(type==="inlineStr")value=[...body.matchAll(/<t\b[^>]*>([\s\S]*?)<\/t>/g)].map(x=>dec(x[1])).join("");else value=dec(body.match(/<v>([\s\S]*?)<\/v>/)?.[1]||"");values.set(colNo(ref),value);}out.push({row,values});}return out;}
function norm(v=""){return String(v).toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu,"").replace(/đ/g,"d").replace(/\b(ky luc gia|klg|gsdd|tsdd|gs|pgs|ts|ths|bs|ong|ba|anh|chi|nghe nhan|nghe si|hoa si|nha suu tap|anh hung lao dong|giao su|bac si|tien si|thac si|phap danh|chau a|viet nam|the gioi)\b/g," ").replace(/[^a-z0-9]+/g," ").replace(/\s+/g," ").trim();}
function variants(v=""){const s=String(v),out=new Set([norm(s),norm(s.replace(/\([^)]*\)/g," "))]);for(const m of s.matchAll(/\(([^)]+)\)/g))out.add(norm(m[1]));return[...out].filter(Boolean);}

const strings=shared();
const full=rows("sheet6.xml",strings).filter(r=>r.row>1).map(r=>({row:r.row,stt:String(r.values.get(1)||"").trim(),title:String(r.values.get(2)||"").trim(),name:String(r.values.get(3)||"").trim(),vars:variants(r.values.get(3)||"")})).filter(r=>r.name);
const standardRows=rows("sheet2.xml",strings).filter(r=>r.row>=3).map(r=>({row:r.row,name:String(r.values.get(7)||"").trim(),gab:String(r.values.get(6)||"").trim(),record:String(r.values.get(5)||r.values.get(14)||"").trim(),vars:variants(r.values.get(7)||"")})).filter(r=>r.name);
const standardNames=new Map();for(const r of standardRows)for(const v of r.vars)if(!standardNames.has(v))standardNames.set(v,r);
const matched=[],missing=[];
for(const p of full){let hit=null;for(const v of p.vars){if(standardNames.has(v)){hit=standardNames.get(v);break;}}if(hit)matched.push({...p,hit});else missing.push({...p,query:`site:kyluc.vn "${p.name}"`,search:`https://www.google.com/search?q=${encodeURIComponent(`site:kyluc.vn "${p.name}"`)}`});}

let styles=read(path.join(xlsx,"xl","styles.xml"));
function append(xml,tag,item){const re=new RegExp(`<${tag}\\b([^>]*)count="(\\d+)"([^>]*)>([\\s\\S]*?)<\\/${tag}>`),m=xml.match(re);if(!m)throw new Error(`Không tìm thấy ${tag}`);return xml.replace(re,`<${tag}${m[1]}count="${Number(m[2])+1}"${m[3]}>${m[4]}${item}</${tag}>`);}
const font=Number(styles.match(/<fonts\b[^>]*count="(\d+)"/)?.[1]||0);styles=append(styles,"fonts",`<font><b/><color rgb="FFFFFFFF"/><sz val="11"/><name val="Arial"/></font>`);
const fill=Number(styles.match(/<fills\b[^>]*count="(\d+)"/)?.[1]||0);for(const c of["FF7F6000","FFFFF2CC","FFFCE4D6"])styles=append(styles,"fills",`<fill><patternFill patternType="solid"><fgColor rgb="${c}"/><bgColor indexed="64"/></patternFill></fill>`);
const xf=Number(styles.match(/<cellXfs\b[^>]*count="(\d+)"/)?.[1]||0);for(const x of[`<xf numFmtId="0" fontId="${font}" fillId="${fill}" borderId="0" xfId="0" applyFont="1" applyFill="1" applyAlignment="1"><alignment vertical="center" wrapText="1"/></xf>`,`<xf numFmtId="0" fontId="0" fillId="${fill+1}" borderId="0" xfId="0" applyFill="1" applyAlignment="1"><alignment vertical="center" wrapText="1"/></xf>`,`<xf numFmtId="0" fontId="0" fillId="${fill+2}" borderId="0" xfId="0" applyFill="1" applyAlignment="1"><alignment vertical="top" wrapText="1"/></xf>`,`<xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0" applyAlignment="1"><alignment vertical="top" wrapText="1"/></xf>`])styles=append(styles,"cellXfs",x);write(path.join(xlsx,"xl","styles.xml"),styles);
const cell=(v,ref,s)=>`<c r="${ref}" s="${s}" t="inlineStr"><is><t xml:space="preserve">${esc(v)}</t></is></c>`,row=(vals,n,style,h=36)=>`<row r="${n}" ht="${h}" customHeight="1">${vals.map((v,i)=>cell(v,`${colName(i+1)}${n}`,Array.isArray(style)?style[i]:style)).join("")}</row>`;
const table=[];table.push(row(["DANH SÁCH KLG CÒN THIẾU DỮ LIỆU - CẦN RESEARCH KYLUC.VN"],1,xf,30));table.push(row([`Full dữ liệu thô: ${full.length} người | Đã có trong tab chuẩn: ${matched.length} người | Còn cần research: ${missing.length} người`],2,xf+1,24));table.push(row(["Chỉ gồm người chưa khớp chắc theo tên với tab 200 người đã chuẩn. Không dùng kết quả tên gần giống để tránh loại nhầm."],3,xf+1,24));table.push(`<row r="4" ht="8" customHeight="1"/>`);
const headers=["STT","TÊN KỶ LỤC GIA","THÔNG TIN TRÊN THẺ","TRẠNG THÁI","TỪ KHÓA RESEARCH","LINK TÌM TRÊN KYLUC.VN","KẾT QUẢ RESEARCH","LINK BÀI VIẾT TÌM ĐƯỢC","GHI CHÚ"];
table.push(row(headers,5,xf,44));missing.forEach((r,i)=>table.push(row([i+1,r.name,r.title,"CHƯA CÓ DỮ LIỆU CHUẨN",r.query,r.search,"CHƯA RESEARCH","",""],i+6,[xf+3,xf+2,xf+3,xf+2,xf+3,xf+3,xf+2,xf+3,xf+3],42)));
const last=missing.length+5,widths=[7,30,42,28,43,58,22,58,45];
const sheet=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetViews><sheetView workbookViewId="0" showGridLines="0"><pane ySplit="5" topLeftCell="A6" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><dimension ref="A1:I${last}"/><cols>${widths.map((w,i)=>`<col min="${i+1}" max="${i+1}" width="${w}" customWidth="1"/>`).join("")}</cols><sheetData>${table.join("")}</sheetData><autoFilter ref="A5:I${last}"/><mergeCells count="3"><mergeCell ref="A1:I1"/><mergeCell ref="A2:I2"/><mergeCell ref="A3:I3"/></mergeCells></worksheet>`;
write(path.join(xlsx,"xl","worksheets","sheet7.xml"),sheet);
let wb=read(path.join(xlsx,"xl","workbook.xml"));wb=wb.replace(/<sheet[^>]*name="CẦN RESEARCH KYLUC.VN"[^>]*\/>/g,"").replace("</sheets>",`<sheet sheetId="7" name="CẦN RESEARCH KYLUC.VN" state="visible" r:id="rId10"/></sheets>`);write(path.join(xlsx,"xl","workbook.xml"),wb);
let rel=read(path.join(xlsx,"xl","_rels","workbook.xml.rels"));rel=rel.replace(/<Relationship[^>]*Id="rId10"[^>]*\/>/g,"").replace("</Relationships>",`<Relationship Id="rId10" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet7.xml"/></Relationships>`);write(path.join(xlsx,"xl","_rels","workbook.xml.rels"),rel);
let types=read(path.join(xlsx,"[Content_Types].xml"));if(!types.includes('/xl/worksheets/sheet7.xml'))types=types.replace("</Types>",`<Override PartName="/xl/worksheets/sheet7.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>`);write(path.join(xlsx,"[Content_Types].xml"),types);
const zip=path.join(work,"updated.zip"),temp=path.join(work,"So sánh.updated.xlsx");if(fs.existsSync(zip))fs.rmSync(zip,{force:true});if(fs.existsSync(temp))fs.rmSync(temp,{force:true});execFileSync("powershell",["-NoProfile","-Command",`Add-Type -AssemblyName System.IO.Compression.FileSystem; [System.IO.Compression.ZipFile]::CreateFromDirectory('${xlsx.replace(/'/g,"''")}', '${zip.replace(/'/g,"''")}')`],{stdio:"pipe"});fs.copyFileSync(zip,temp);fs.copyFileSync(temp,source);
console.log(JSON.stringify({source,fullPeople:full.length,standardAchievementRows:standardRows.length,matchedPeople:matched.length,missingPeople:missing.length},null,2));
