import fs from "node:fs";import path from "node:path";import{execFileSync}from"node:child_process";
const root=process.cwd(),work=path.join(root,"outputs","complete_standard_work"),xlsx=path.join(work,"xlsx"),source=path.join(root,"Dulieutruyxuat","So sánh.xlsx");
const dec=s=>String(s||"").replace(/&#x([0-9a-f]+);/gi,(_,x)=>String.fromCodePoint(parseInt(x,16))).replace(/&#(\d+);/g,(_,x)=>String.fromCodePoint(+x)).replace(/&amp;/g,"&").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&quot;/g,'"');
const norm=s=>String(s||"").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu,"").replace(/[^a-z0-9]+/g," ").trim();
const ssPath=path.join(xlsx,"xl","sharedStrings.xml"),ss=fs.existsSync(ssPath)?[...fs.readFileSync(ssPath,"utf8").matchAll(/<si\b[^>]*>([\s\S]*?)<\/si>/g)].map(m=>[...m[1].matchAll(/<t\b[^>]*>([\s\S]*?)<\/t>/g)].map(x=>dec(x[1])).join("")):[];
function value(body,attrs){const t=attrs.match(/\bt="([^"]+)"/)?.[1]||"";if(t==="s")return ss[+(body.match(/<v>([\s\S]*?)<\/v>/)?.[1]||0)]||"";if(t==="inlineStr")return[...body.matchAll(/<t\b[^>]*>([\s\S]*?)<\/t>/g)].map(x=>dec(x[1])).join("");return dec(body.match(/<v>([\s\S]*?)<\/v>/)?.[1]||"");}
const map=new Map(),s1=fs.readFileSync(path.join(xlsx,"xl","worksheets","sheet1.xml"),"utf8");for(const r of s1.matchAll(/<row\b[^>]*>([\s\S]*?)<\/row>/g)){const v={};for(const c of r[1].matchAll(/<c\b([^>]*)>([\s\S]*?)<\/c>/g)){const ref=c[1].match(/\br="([A-Z]+)/)?.[1];if(ref)v[ref]=value(c[2],c[1]);}if(v.D&&/^https?:\/\/gab\.world\//i.test(v.C||""))map.set(norm(v.D),v.C);}
const file=path.join(xlsx,"xl","worksheets","sheet2.xml");let xml=fs.readFileSync(file,"utf8"),updated=0;xml=xml.replace(/<row\b([^>]*)>([\s\S]*?)<\/row>/g,(whole,attrs,body)=>{const row=attrs.match(/\br="(\d+)"/)?.[1];if(!row)return whole;let name="",gab="";for(const c of body.matchAll(/<c\b([^>]*)>([\s\S]*?)<\/c>/g)){const ref=c[1].match(/\br="([A-Z]+)/)?.[1],v=value(c[2],c[1]);if(ref==="G")name=v;if(ref==="F")gab=v;}const link=map.get(norm(name));if(!link||!/^Chưa có GAB$/i.test(gab))return whole;updated++;const replacement=`<c r="F${row}" s="1" t="inlineStr"><is><t xml:space="preserve">${link.replace(/&/g,"&amp;")}</t></is></c>`;return`<row${attrs}>${body.replace(/<c\b[^>]*\br="F\d+"[^>]*>[\s\S]*?<\/c>/,replacement)}</row>`;});fs.writeFileSync(file,xml);
const zip=path.join(work,"gab_filled.zip");if(fs.existsSync(zip))fs.rmSync(zip,{force:true});execFileSync("powershell",["-NoProfile","-Command",`Add-Type -AssemblyName System.IO.Compression.FileSystem; [IO.Compression.ZipFile]::CreateFromDirectory('${xlsx.replace(/'/g,"''")}','${zip.replace(/'/g,"''")}')`]);fs.copyFileSync(zip,source);console.log(JSON.stringify({updated,source},null,2));
