import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';

const root=process.cwd(), srcDir=path.join(root,'outputs','compare_19_09_2026'), outDir=path.join(root,'outputs','clean_19_09_2026');
fs.rmSync(outDir,{recursive:true,force:true}); fs.mkdirSync(path.join(outDir,'_rels'),{recursive:true}); fs.mkdirSync(path.join(outDir,'xl','_rels'),{recursive:true}); fs.mkdirSync(path.join(outDir,'xl','worksheets'),{recursive:true});
const read=p=>fs.readFileSync(p,'utf8'); const write=(p,s)=>fs.writeFileSync(p,s,'utf8');
const dec=(s='')=>s.replace(/&#x([0-9a-f]+);/gi,(_,x)=>String.fromCodePoint(parseInt(x,16))).replace(/&#(\d+);/g,(_,x)=>String.fromCodePoint(+x)).replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&apos;/g,"'").replace(/&amp;/g,'&');
const clean=s=>String(s??'').replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F]/g,'');
const esc=s=>clean(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const shared=[...read(path.join(srcDir,'xl','sharedStrings.xml')).matchAll(/<si\b[^>]*>([\s\S]*?)<\/si>/g)].map(m=>[...m[1].matchAll(/<t\b[^>]*>([\s\S]*?)<\/t>/g)].map(x=>dec(x[1])).join(''));
const colNo=s=>{let n=0;for(const c of s)n=n*26+c.charCodeAt(0)-64;return n}; const colName=n=>{let s='';while(n){const r=(n-1)%26;s=String.fromCharCode(65+r)+s;n=Math.floor((n-1)/26)}return s};
function parseSheet(file){const xml=read(path.join(srcDir,'xl','worksheets',file)), rows=[];for(const m of xml.matchAll(/<row\b([^>]*)>([\s\S]*?)<\/row>/g)){const n=+m[1].match(/\br="(\d+)"/)?.[1],v={};for(const c of m[2].matchAll(/<c\b([^>]*?)(?:\/>|>([\s\S]*?)<\/c>)/g)){const ref=c[1].match(/\br="([A-Z]+)\d+"/)?.[1];if(!ref)continue;const type=c[1].match(/\bt="([^"]+)"/)?.[1],body=c[2]||'';let value='';if(type==='s')value=shared[+(body.match(/<v>([\s\S]*?)<\/v>/)?.[1]??-1)]??'';else if(type==='inlineStr')value=[...body.matchAll(/<t\b[^>]*>([\s\S]*?)<\/t>/g)].map(x=>dec(x[1])).join('');else value=dec(body.match(/<v>([\s\S]*?)<\/v>/)?.[1]??'');v[colNo(ref)]=value}rows.push({n,v})}return rows}
const date=v=>{const s=String(v??'');if(/^\d+(\.0+)?$/.test(s)){const x=+s;if(x>20000&&x<70000){const d=new Date(Date.UTC(1899,11,30)+x*86400000);return `${String(d.getUTCDate()).padStart(2,'0')}/${String(d.getUTCMonth()+1).padStart(2,'0')}/${d.getUTCFullYear()}`}}return s.replace(/\.0$/,'')};
const hasData=r=>Object.values(r.v).some(v=>String(v??'').trim()!=='');
const s1=parseSheet('sheet1.xml').filter(hasData); const s2=parseSheet('sheet2.xml').filter(hasData); const s3=parseSheet('sheet3.xml').filter(hasData);
for(const r of s1)if(r.n>1)r.v[4]=date(r.v[4]); for(const r of s2)if(r.n>2){r.v[4]=date(r.v[4]);r.v[13]=date(r.v[13])}
function sheetXml(rows,maxCol,{freeze=1,filterRow=1,merges=[],widths=[]}={}){const last=Math.max(...rows.map(r=>r.n)), isCompare=maxCol>=39, cells=rows.map(r=>{const vals=[];for(let c=1;c<=maxCol;c++){if(r.v[c]===undefined||r.v[c]==='')continue;let style=r.n===filterRow?1:(r.n<filterRow?2:(c<=10?3:(c<=30?4:5)));if(isCompare&&r.n>filterRow){const status=String(r.v[2]||''),value=String(r.v[c]||'');if(c>=2&&c<=4){style=status.includes('ĐỦ - KHỚP')?8:(status.includes('THIẾU')||status.includes('CHƯA CÓ HỒ SƠ')?6:7)}else if(/^(CHƯA CÓ|KHÔNG CÓ|KHÔNG TÌM THẤY|GAB THIẾU)/.test(value))style=9;else if(c>=36)style=5;else if(c>=16&&c<=35)style=4;else style=3}vals.push(`<c r="${colName(c)}${r.n}" s="${style}" t="inlineStr"><is><t xml:space="preserve">${esc(r.v[c])}</t></is></c>`)}const h=r.n===filterRow?' ht="54" customHeight="1"':(r.n<filterRow?' ht="28" customHeight="1"':(isCompare?' ht="76" customHeight="1"':' ht="48" customHeight="1"'));return `<row r="${r.n}"${h}>${vals.join('')}</row>`}).join('');const cols=widths.length?`<cols>${widths.map((w,i)=>`<col min="${i+1}" max="${i+1}" width="${w}" customWidth="1"/>`).join('')}</cols>`:'';const mergeXml=merges.length?`<mergeCells count="${merges.length}">${merges.map(x=>`<mergeCell ref="${x}"/>`).join('')}</mergeCells>`:'';return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><dimension ref="A1:${colName(maxCol)}${last}"/><sheetViews><sheetView workbookViewId="0" showGridLines="0"><pane xSplit="${isCompare?4:0}" ySplit="${freeze}" topLeftCell="${isCompare?'E':'A'}${freeze+1}" activePane="bottomRight" state="frozen"/></sheetView></sheetViews>${cols}<sheetData>${cells}</sheetData><autoFilter ref="A${filterRow}:${colName(maxCol)}${last}"/>${mergeXml}</worksheet>`}
write(path.join(outDir,'xl','worksheets','sheet1.xml'),sheetXml(s1,7,{freeze:1,filterRow:1,widths:[24,48,28,16,68,55,80]}));
write(path.join(outDir,'xl','worksheets','sheet2.xml'),sheetXml(s2,20,{freeze:2,filterRow:2,widths:[9,20,20,16,65,48,28,12,20,35,25,25,18,65,50,80,45,45,45,60]}));
write(path.join(outDir,'xl','worksheets','sheet3.xml'),sheetXml(s3,43,{freeze:6,filterRow:6,merges:['A1:AQ1','A2:AQ2','A3:AQ3','A4:AQ4'],widths:[28,34,48,50,11,13,14,16,17,72,72,72,16,72,14,10,20,18,16,58,47,28,12,20,35,23,24,18,58,48,68,45,45,45,56,23,47,28,15,58,48,68,13]}));
write(path.join(outDir,'[Content_Types].xml'),'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/worksheets/sheet2.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/worksheets/sheet3.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>');
write(path.join(outDir,'_rels','.rels'),'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>');
write(path.join(outDir,'xl','workbook.xml'),'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="DANH SÁCH ĐẦY ĐỦ TRÊN GAB" sheetId="1" r:id="rId1"/><sheet name="Danh sách 200 người đã chuẩn" sheetId="2" r:id="rId2"/><sheet name="ĐỐI CHIẾU GAB - 200" sheetId="3" r:id="rId3"/></sheets></workbook>');
write(path.join(outDir,'xl','_rels','workbook.xml.rels'),'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet2.xml"/><Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet3.xml"/><Relationship Id="rId4" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>');
write(path.join(outDir,'xl','styles.xml'),'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="2"><font><sz val="10"/><name val="Arial"/></font><font><b/><color rgb="FFFFFFFF"/><sz val="10"/><name val="Arial"/></font></fonts><fills count="10"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF17365D"/><bgColor indexed="64"/></patternFill></fill><fill><patternFill patternType="solid"><fgColor rgb="FFD9EAF7"/><bgColor indexed="64"/></patternFill></fill><fill><patternFill patternType="solid"><fgColor rgb="FFF2F2F2"/><bgColor indexed="64"/></patternFill></fill><fill><patternFill patternType="solid"><fgColor rgb="FFEAF3F8"/><bgColor indexed="64"/></patternFill></fill><fill><patternFill patternType="solid"><fgColor rgb="FFF4CCCC"/><bgColor indexed="64"/></patternFill></fill><fill><patternFill patternType="solid"><fgColor rgb="FFFFE5B4"/><bgColor indexed="64"/></patternFill></fill><fill><patternFill patternType="solid"><fgColor rgb="FFE2F0D9"/><bgColor indexed="64"/></patternFill></fill><fill><patternFill patternType="solid"><fgColor rgb="FFFFF2CC"/><bgColor indexed="64"/></patternFill></fill></fills><borders count="1"><border><left/><right/><top/><bottom/><diagonal/></border></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="10"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/><xf numFmtId="0" fontId="1" fillId="2" borderId="0" xfId="0" applyFont="1" applyFill="1" applyAlignment="1"><alignment horizontal="center" vertical="center" wrapText="1"/></xf><xf numFmtId="0" fontId="1" fillId="2" borderId="0" xfId="0" applyFont="1" applyFill="1" applyAlignment="1"><alignment vertical="center" wrapText="1"/></xf><xf numFmtId="0" fontId="0" fillId="3" borderId="0" xfId="0" applyFill="1" applyAlignment="1"><alignment vertical="top" wrapText="1"/></xf><xf numFmtId="0" fontId="0" fillId="4" borderId="0" xfId="0" applyFill="1" applyAlignment="1"><alignment vertical="top" wrapText="1"/></xf><xf numFmtId="0" fontId="0" fillId="5" borderId="0" xfId="0" applyFill="1" applyAlignment="1"><alignment vertical="top" wrapText="1"/></xf><xf numFmtId="0" fontId="0" fillId="6" borderId="0" xfId="0" applyFill="1" applyAlignment="1"><alignment vertical="top" wrapText="1"/></xf><xf numFmtId="0" fontId="0" fillId="7" borderId="0" xfId="0" applyFill="1" applyAlignment="1"><alignment vertical="top" wrapText="1"/></xf><xf numFmtId="0" fontId="0" fillId="8" borderId="0" xfId="0" applyFill="1" applyAlignment="1"><alignment vertical="top" wrapText="1"/></xf><xf numFmtId="0" fontId="0" fillId="9" borderId="0" xfId="0" applyFill="1" applyAlignment="1"><alignment vertical="top" wrapText="1"/></xf></cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles></styleSheet>');
const zip=path.join(root,'outputs','19_09_2026_clean.zip'), target=path.join(root,'Dulieutruyxuat','19_09_2026.xlsx'); if(fs.existsSync(zip))fs.rmSync(zip,{force:true});execFileSync('powershell',['-NoProfile','-Command',`Add-Type -AssemblyName System.IO.Compression.FileSystem; [IO.Compression.ZipFile]::CreateFromDirectory('${outDir.replace(/'/g,"''")}','${zip.replace(/'/g,"''")}')`]);fs.copyFileSync(zip,target);console.log(JSON.stringify({target,sheet1Rows:s1.length,sheet2Rows:s2.length,sheet3Rows:s3.length},null,2));
