import fs from"node:fs";import path from"node:path";import{execFileSync}from"node:child_process";const root=process.cwd(),work=path.join(root,"outputs","complete_standard_work"),xlsx=path.join(work,"xlsx"),source=path.join(root,"Dulieutruyxuat","So sánh.xlsx");
const records=[
["TRẦN QUANG LÂN","22/03/2026","Nhà bè triển khai mô hình nuôi thủy sản lồng bè kết hợp du lịch trải nghiệm trên Vịnh Di sản có quy mô lớn nhất Việt Nam","KỶ LỤC VIỆT NAM","https://kyluc.vn/tin-tuc/ky-luc/nha-be-hai-phong-dau-an-kep-ky-luc-viet-nam-giua-vinh-lan-ha"],
["TRẦN QUANG LÂN","22/03/2026","Nhà bè nổi trên Vịnh Di sản có 02 tuyến đường đi bộ nội khu song song dài nhất Việt Nam","KỶ LỤC VIỆT NAM","https://kyluc.vn/tin-tuc/ky-luc/nha-be-hai-phong-dau-an-kep-ky-luc-viet-nam-giua-vinh-lan-ha"],
["TRẦN VĂN TOẢN","20/05/2023","Tháp Thần Nông - Tháp cối đá tạo hình hạt lúa lớn nhất Việt Nam","KỶ LỤC VIỆT NAM","https://kyluc.vn/tin-tuc/ky-luc/doc-dao-thap-than-nong-hinh-hat-lua-ghep-tu-1012-chiec-coi-da-lon-nhat-viet-nam"],
["TRẦN VĂN TOẢN","30/11/2023","Tháp Thần Nông - Bảo tháp làm bằng cối đá, tạo hình hạt lúa có kích thước lớn nhất châu Á","KỶ LỤC CHÂU Á","https://kyluc.vn/tin-tuc/ky-luc-chau-a/la-ky-bao-thap-than-nong-tu-1-012-coi-da-tao-hinh-hat-lua-lon-nhat-dat-ky-luc-chau-a-1"],
["TRẦN VĂN TOẢN","13/10/2024","Đông Đô Village - Khu du lịch văn hóa sinh thái có công trình Tháp Thần Nông tạo hình hạt lúa ghép từ nhiều cối đá nhất thế giới","KỶ LỤC THẾ GIỚI","https://kyluc.vn/tin-tuc/ky-luc-the-gioi/dong-do-village-thap-than-nong-hinh-hat-lua-tu-1-012-coi-da-duoc-vinh-danh-ky-luc-the-gioi"],
["NGUYÊN MẠNH PHƯƠNG (NGUYẼN PHƯƠNG)","06/05/2017","Ảo thuật gia biểu diễn tương tác với màn hình LED 3D mới lạ và độc đáo","KỶ LỤC VIỆT NAM","https://kyluc.vn/tin-tuc/ky-luc/ao-thuat-gia-nguyen-phuong-xac-lap-ky-luc-viet-nam-tai-hoi-ngo-ky-luc-gia-lan-thu-33"],
["NGUYÊN MẠNH PHƯƠNG (NGUYẼN PHƯƠNG)","10/06/2017","Tiết mục ảo thuật tương tác với màn hình LED theo công nghệ 4D","KỶ LỤC VIỆT NAM","https://kyluc.vn/tin-tuc/ky-luc/ao-thuat-gia-nguyen-phuong-tiep-tuc-xac-lap-ky-luc-viet-nam-voi-man-bieu-dien-tuong-tac-4d"],
["NGUYÊN MẠNH PHƯƠNG (NGUYẼN PHƯƠNG)","26/08/2018","Ảo thuật gia có màn trình diễn ảo thuật 4D tương tác với màn hình LED đầu tiên trên thế giới","KỶ LỤC THẾ GIỚI","https://kyluc.vn/tin-tuc/ky-luc/xac-lap-them-4-ky-luc-the-gioi-moi-tai-viet-nam"]];
const norm=s=>String(s||"").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu,"").replace(/[^a-z0-9]+/g," ").trim(),resolved=new Set(records.map(r=>norm(r[0]))),esc=v=>String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;"),dec=s=>String(s||"").replace(/&amp;/g,"&").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&quot;/g,'"'),col=n=>{let s="";while(n){s=String.fromCharCode(65+(n-1)%26)+s;n=Math.floor((n-1)/26);}return s;};
const file=path.join(xlsx,"xl","worksheets","sheet2.xml");let xml=fs.readFileSync(file,"utf8");xml=xml.replace(/<row\b([^>]*)>([\s\S]*?)<\/row>/g,(w,a,b)=>{const name=[...b.matchAll(/<c\b[^>]*\br="G\d+"[^>]*>[\s\S]*?<t\b[^>]*>([\s\S]*?)<\/t>[\s\S]*?<\/c>/g)][0]?.[1]||"",type=[...b.matchAll(/<c\b[^>]*\br="K\d+"[^>]*>[\s\S]*?<t\b[^>]*>([\s\S]*?)<\/t>[\s\S]*?<\/c>/g)][0]?.[1]||"";return resolved.has(norm(dec(name)))&&dec(type)==="CHƯA XÁC MINH"?"":w;});
let start=Math.max(...[...xml.matchAll(/<row\b[^>]*\br="(\d+)"/g)].map(m=>+m[1]))+1;const sample=xml.match(/<row\b[^>]*\br="3"[^>]*>([\s\S]*?)<\/row>/)?.[1]||"",styles=new Map();for(const c of sample.matchAll(/<c\b([^>]*)/g)){const k=c[1].match(/\br="([A-Z]+)3"/)?.[1],s=c[1].match(/\bs="(\d+)"/)?.[1];if(k)styles.set(k,s||"0");}const cell=(v,r,c)=>`<c r="${c}${r}" s="${styles.get(c)||1}" t="inlineStr"><is><t xml:space="preserve">${esc(v)}</t></is></c>`;const block=records.map((x,i)=>{const r=start+i,[name,date,title,type,url]=x,vals=["","","",date,title,"Chưa có GAB",name,"","","",type,"",date,`Xác lập ${type.toLowerCase()} “${title}”`,url,"","","","Bổ sung từ bài Kyluc.vn đã kiểm chứng.",""];return`<row r="${r}" ht="42" customHeight="1">${vals.map((v,j)=>cell(v,r,col(j+1))).join("")}</row>`}).join("");const last=start+records.length-1;xml=xml.replace("</sheetData>",`${block}</sheetData>`).replace(/<dimension ref="[^"]+"\/>/,`<dimension ref="A1:T${last}"/>`);fs.writeFileSync(file,xml);const zip=path.join(work,"resolved_more.zip");if(fs.existsSync(zip))fs.rmSync(zip,{force:true});execFileSync("powershell",["-NoProfile","-Command",`Add-Type -AssemblyName System.IO.Compression.FileSystem; [IO.Compression.ZipFile]::CreateFromDirectory('${xlsx.replace(/'/g,"''")}','${zip.replace(/'/g,"''")}')`]);fs.copyFileSync(zip,source);console.log(JSON.stringify({resolvedPeople:resolved.size,added:records.length,start,last},null,2));
